import json
import base64
import math
from typing import Dict, Tuple

# Ofansif kodundaki GERÇEK sınıf adını (EncryptedC2Channel) içe aktarıyoruz
from offensive_c2_channel import EncryptedC2Channel


class BlueTeamC2Detector:
    def __init__(self, entropy_threshold: float = 4.0):
        self.entropy_threshold = entropy_threshold
        self.suspicious_events = []
    
    # 1. ADIM: Shannon Entropisi Hesaplama
    def calculate_entropy(self, data_bytes: bytes) -> float:
        if not data_bytes:
            return 0.0
        
        byte_counts = {}
        for b in data_bytes:
            byte_counts[b] = byte_counts.get(b, 0) + 1
        
        entropy = 0.0
        length = len(data_bytes)
        for count in byte_counts.values():
            probability = count / length
            entropy -= probability * math.log2(probability)
        
        return entropy
    
    # 2. ADIM: Ağ Paketini İnceleme (Ağ Bekçisi / NIDS)
    def inspect_packet(self, packet_raw: str) -> Tuple[bool, Dict]:
        try:
            payload = json.loads(packet_raw)
        except json.JSONDecodeError:
            return False, {"reason": "Not a valid JSON format"}
        
        if "nonce" not in payload or "ciphertext" not in payload:
            return False, {"reason": "JSON structural anomaly: Missing C2 keys"}
        
        try:
            nonce_bytes = base64.b64decode(payload["nonce"])
            ciphertext_bytes = base64.b64decode(payload["ciphertext"])
        except Exception:
            return False, {"reason": "Base64 decoding failed"}
        
        nonce_len = len(nonce_bytes)
        ciphertext_entropy = self.calculate_entropy(ciphertext_bytes)
        
        is_suspicious = False
        findings = {
            "nonce_bytes_len": nonce_len,
            "ciphertext_entropy": round(ciphertext_entropy, 4),
            "threat_detected": False
        }
        
        # Karar Mekanizması: 12 baytlık Nonce VEYA Yüksek Entropi
        if nonce_len == 12 or ciphertext_entropy > self.entropy_threshold:
            is_suspicious = True
            findings["threat_detected"] = True
            findings["signature"] = "SUSPICIOUS_AES_GCM_C2_CHANNEL"
            self.suspicious_events.append(findings)
        
        return is_suspicious, findings
    
    # 3. ADIM: Adli Bilişim (Şifre Çözme Denemesi)
    def attempt_break_or_validate(self, packet_raw: str, candidate_passphrase: str, salt: bytes) -> Tuple[bool, str]:
        from cryptography.hazmat.primitives.ciphers.aead import AESGCM
        from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
        from cryptography.hazmat.primitives import hashes
        
        try:
            payload = json.loads(packet_raw)
            nonce = base64.b64decode(payload["nonce"])
            ciphertext = base64.b64decode(payload["ciphertext"])
            
            kdf = PBKDF2HMAC(
                algorithm=hashes.SHA256(),
                length=32,
                salt=salt,
                iterations=100_000
            )
            key = kdf.derive(candidate_passphrase.encode('utf-8'))
            cipher = AESGCM(key)
            
            decrypted_bytes = cipher.decrypt(nonce, ciphertext, associated_data=None)
            return True, decrypted_bytes.decode('utf-8')
        except Exception as e:
            return False, f"Decryption Failed: {str(e)}"


# =====================================================================
# =====================================================================
if __name__ == "__main__":
    
    # 1. Defining the REAL secret passphrase from the offensive code
    SECRET_PASSPHRASE = "CyberKillChain_MasterKey_2026!"
    
    # 2. Initializing our offensive object
    attacker = EncryptedC2Channel(shared_passphrase=SECRET_PASSPHRASE)
    
    # 3. Generating a live packet using the REAL 'encrypt_payload' method from the offensive code
    live_packet = attacker.encrypt_payload("whoami")
    
    print("\n==================================================")
    print(" BLUE TEAM LIVE C2 DETECTION AND ANALYSIS SIMULATION")
    print("==================================================")
    print(f"\n[1] Live Packet Generated by the Attacker:\n{live_packet}")

    # 4. Our Blue Team Detector captures and inspects the packet
    detector = BlueTeamC2Detector()
    is_suspicious, findings = detector.inspect_packet(live_packet)
    
    print("\n[2] Blue Team NIDS Detection Result:")
    print(f"-> Is Suspicious/Malicious? : {is_suspicious}")
    print(f"-> Analysis Details         : {findings}")

    # 5. Blue Team Decrypts the Payload Using the Intercepted Passphrase and Salt
    success, decrypted_text = detector.attempt_break_or_validate(
        live_packet, 
        candidate_passphrase=SECRET_PASSPHRASE, 
        salt=attacker.salt
    )
    print("\n[3] Digital Forensics Decryption Result:")
    print(f"-> Successful?       : {success}")
    print(f"-> Decrypted Text    : '{decrypted_text}'")